### ISSUE TITLE
 ReferenceError: document is not defined

### ISSUE THREAD

**Issue by bperel** [canvg/canvg#1286]
Hello,

When trying to render an SVG with an image and a rectangle as shown below, I get the following error :
`Error while loading image "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAIAAAACDbGyAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAfSURBVBhXY/iPCnDwOTk5mZiYEHwgh4EBxEZV//8/AEZCPunvSPG3AAAAAElFTkSuQmCC": ReferenceError: document is not defined`

The PNG gets generated, but without the embedded image.

SVG output| canvg output
------------ | -------------
![image](https://user-images.githubusercontent.com/1484692/101484478-fc23a880-3959-11eb-8e91-369ededd03e4.png) | ![image](https://user-images.githubusercontent.com/1484692/101484566-1fe6ee80-395a-11eb-844c-4849660112d7.png)

```js
const fs = require('fs')
const svg2img = require('svg2img')

const svgString =
  '<svg viewBox="0 0 18 450" width="27" height="675" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" preserveAspectRatio="none">' +
    '<g class="Image">' +
      '<image preserveAspectRatio="none" x="2" y="32" width="15" height="15" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAIAAAACDbGyAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAfSURBVBhXY/iPCnDwOTk5mZiYEHwgh4EBxEZV//8/AEZCPunvSPG3AAAAAElFTkSuQmCC" style=""> </image> ' +
    '</g>' +
    '<rect id="border" x="1" y="1" width="16" height="448" fill="none" stroke="black" stroke-width="1.5"></rect>' +
  '</svg>'

svg2img(svgString, (error, buffer) => {
  fs.writeFileSync('foo1.png', buffer)
})
```

**Comment by gabelerner** [comment]
The svg here and in the thread work on browser:

http://canvg.github.io/canvg/demo/index.html
![image](https://user-images.githubusercontent.com/241819/101511125-6d019b00-392f-11eb-9ec9-c49a98820293.png)
![image](https://user-images.githubusercontent.com/241819/101512200-a89c6500-392f-11eb-9c56-ef94b0875453.png)

it seems like the original issue is referencing:
```
Looks like caused by mask element's parsing in the svg.
It should be a bug of upstream canvg, it shouldn't use document.createCanvas in node environment.
```

we aren't using `document` on node, we have a separate interface:
https://github.com/canvg/canvg/blob/22ad6475894f316c76cc2d15a1e768829428106a/src/presets/node.ts#L51

it seems on this line: https://github.com/fuzhenn/node-svg2img/blob/8995b92519380f0422ea316563f2c0bdac704341/index.js#L72 our interface isn't used correctly since they aren't passing a reference to `createCanvas`. I'll comment there as well.

**Comment by bperel** [comment]
Thank you for your detailed response @gabelerner , you are right that the issue seems to be on svg2img's side.
