### ISSUE TITLE
Official npm package

### ISSUE THREAD

**Issue by felixfbecker** [canvg/canvg#425]
I'm currently preparing a pull request for https://github.com/A----/highcharts-export-clientside/issues/27, which depends on this. It would be nice if I could add this package as an actual dependency with a semver version constraint instead of locking it to a git commit.

It seems like https://www.npmjs.com/package/canvg is _not_ an official package and also says it's a "port" and that "all browser-specific code has to be removed". Could you maybe publish an official package at NPM if @yetzt makes the name available, so this can be properly depended on?

**Comment by yetzt** [comment]
yes, it's indeed. a year ago the original developers reached out to me if i'd be willing to give up the package so they could publish the official one under that name. i said i'd be willing if the official package would maintain the same apis, work in nodejs and not break any package dependents; they told me they'd merge at some point and reach out to me when they're ready. i heard nothing since.

**Comment by yetzt** [comment]
just had a quick look into it, this implementation is still pretty much focussed on a browser, relying on dom interfaces.

**Comment by felixfbecker** [comment]
Thanks for the reply. Looking at the source code, they definitely make use of `document`. Is this really required? If yes, one could easily make it work in node with jsdom. I would offer to do a PR if this can be solved by some refactoring?

**Comment by felixfbecker** [comment]
What did you change in your node wrapper?

**Comment by yetzt** [comment]
my code is based on a older and simpler version of canvg from three years ago. i used `xmldom` to stand in for the browser dom and went from there, the [early commit history](https://github.com/yetzt/node-canvg/commits/master?page=2) gives a good overview. :)

**Comment by felixfbecker** [comment]
My problem with this is that folks developing for browser will have to pull in an DOMParser shim even though DOMParser is widely supported in all browsers. I would prefer if it would look for a global DOM by default and on Node it would either work with a contructor argument that passes a document from jsdom or xmldom or whatever is needed.

**Comment by yetzt** [comment]
if you make it happen, i'm happily signing the npm package over to @gabelerner. but i guess there is some heavy restructuring needed. good luck.

**Comment by gabelerner** [comment]
i've been kind of afk on this project, but i'll go through PRs soon and merge where appropriate. can definitely add more owners to it as well if there's interest in pushing towards something that works w/ both node and browsers

**Comment by felixfbecker** [comment]
@gabelerner That would be awesome of course, if I could understand the codebase....
Maybe you could explain a bit how it is structured? Thats way to many LOC in one file for me

**Comment by gabelerner** [comment]
most of it isn't dom dependent and i've been meaning to break it out by element into separate files and compile them all together.

it's basically broken up into:
- parse svg dom into canvg nodes
  - base node parses attributes/styles/things common to all nodes
  - each node individually parses its own values (i.e. path would parse the path)
  - child nodes parse themselves recursively
- loop to render every frame
  - calls render on root node
  - each node is responsible for rendering itself and calling render on child objects

99% of the file are the nodes/parsing logic, the only dom logic is in originally parsing it using dom parser and then writing to/manipulating the canvas.

**Comment by felixfbecker** [comment]
So the initial DOM access could be avoided by passing a `document` or `Node` object instead of a string? I saw that you are using `DOMParser` API

**Comment by gabelerner** [comment]
yea in theory, i can split up the dom stuff out of it and then compile 2 versions of canvg - one for browser and one for node too, might take on that project

**Comment by felixfbecker** [comment]
@gabelerner I would fancy an isomorphic version that works in both. When you pass a string as svg, there should be a check if DOMParser is available, if not, it throws an exception. So on Node you can pass a document you parsed with xmldom or jsdom and on the browser you can additionally pass a string for convenience. Should also improve performance if you already have a document object at hand.

Let me know where I can help out

**Comment by gabelerner** [comment]
honestly it's just about me getting some free time ... unfortunately, this repo is not at the top of my priorities these days.  

if you want to help, my ideas would be something like:
- choose gulp or grunt or whatever the rage is these days
- split up every node into a separate file, for example
```javascript
		// group element
		svg.Element.g = function(node) {
                ...
                }
```
can go into `nodes/g.js`
- split up drawSvg implementation, render loop, dom load, into their own files
- make sure gulp/grunt produces the same output as the original
- open a PR with all that
- now canvg can compile various version of canvg for browser vs node, or even add sniffing easily by picking and choosing files and future PRs will be very easy to target certain parts.  for example, we'd be able to just modify the xml parse file and extend it with your last suggestion

**Comment by felixfbecker** [comment]
@gabelerner I initially was interested in this because I wanted to improve Highcharts client-side export module, which depends on this. I recently found out that the desired feature is now included in Highcharts core, so I cannot spend time on improving this anymore, unfortunately.

**Comment by graingert** [comment]
@gabelerner any chance of an official npm package with a different name?

**Comment by jnachtigall** [comment]
I'm puzzled. I'd like to use canvg with webpack and using es6 modules to import. It should run in the browser. So which of the npm packages can I use? Searching https://www.npmjs.com/search?q=canvg reveals many, many options. At the moment I just did `npm install canvg-browser --save-dev` but I am not sure this is the right package for canvg in the browser?

**Comment by dosentmatter** [comment]
@jnachtigall I don't think there's an official npm package, but here's what I can figure out from some digging around:

Keep in mind I haven't tested any of these packages/repos.

[canvg](https://www.npmjs.com/package/canvg):
Port of an old version of canvg. This was when canvg was still on [google code](http://code.google.com/p/canvg/). But now that link just redirects to the [official canvg github repo](https://github.com/canvg/canvg) by Gabe Lerner. The github repo is [node-canvg](https://github.com/yetzt/node-canvg). Looking at the code, it hasn't merged in any recent changes from the official canvg repo.
The good thing about this package is that it will work on node. The way it works is that it uses [`xmldom`](https://www.npmjs.com/package/xmldom) on this [line](https://github.com/yetzt/node-canvg/blob/master/index.js#L135) instead of `document` on the browser. It also uses ['The Cairo backed canvas'](https://www.npmjs.com/package/canvas) instead of `canvas` on the browser.
Another benefit is that it has dependencies on [`rgbcolor`](https://www.npmjs.com/package/rgbcolor)  and [`stackblur`](https://www.npmjs.com/package/stackblur) instead of including them as files in the package like the official canvg does: [rgbcolor included](https://github.com/canvg/canvg/blob/master/rgbcolor.js), [stackblur included](https://github.com/canvg/canvg/blob/master/StackBlur.js).
rgbcolor and stackblur are written by [Stoyan Stefanov](https://github.com/canvg/canvg/blob/master/rgbcolor.js#L3) and [Mario Klingemann](https://github.com/canvg/canvg/blob/master/StackBlur.js#L6) respectively. They don't receive many updates so it's probably fine if you use the npm package or the ones from the official canvg repo (not the original source of rgbcolor and stackblur).
You probably don't want to use the canvg package on the browser because it depends on `xmldom` and `canvas` which the browser already has. It might not work on the browser because `canvas` for node needs Cairo installed. But node `canvas` has a [browser api now](https://github.com/Automattic/node-canvas/blob/master/browser.js) so it might be able to work on the browser.

[canvg-client](https://www.npmjs.com/package/canvg-client):
This is a [fork](https://github.com/syntheticore/node-canvg) of the [canvg package](https://www.npmjs.com/package/canvg) [github repo](https://github.com/yetzt/node-canvg). All it does is [remove dependencies on the node `canvas` package](https://github.com/syntheticore/node-canvg/commit/04951433b78bfb47014b56c9b97073bcd789b322). It uses [`document.createElement('canvas')`](https://github.com/syntheticore/node-canvg/commit/04951433b78bfb47014b56c9b97073bcd789b322#diff-04c6e90faac2675aa89e2176d2eec7d8R12), so it pretty much assumes you are in a browser environment. It still uses [`xmldom`](https://github.com/syntheticore/node-canvg/blob/04951433b78bfb47014b56c9b97073bcd789b322/index.js#L8). I don't really see the point in that because you could just use `document` since you are in the browser.

[canvg-loader](https://www.npmjs.com/package/canvg-loader):
This is a webpack loader using [canvg-client](https://www.npmjs.com/package/canvg-client) is a [fork](https://github.com/syntheticore/node-canvg).

[canvg-fixed](https://www.npmjs.com/package/canvg-fixed):
This is an unofficial package of the official canvg repo. It was published 2 years (Wed Jan 20 07:12:47 UTC 2016) ago so it doesn't have the recent canvg commits. It has rgbcolor and stackblur as dependencies but still includes them as files in the package for some reason. It only works for the browser.

[canvg-origin](https://www.npmjs.com/package/canvg-origin):
This is an unofficial package of the official canvg repo, similar to [canvg-fixed](https://www.npmjs.com/package/canvg-fixed) above. However, it was published 1 year ago (Tue Aug 30 12:44:17 UTC 2016) so it is more recent than canvg-fixed, but it still doesn't have the recent canvg commits. It has rgbcolor and stackblur as dependencies and it doesn't include them as files in the package. It shouldn't matter but the code has a bunch of carriage returns. It only works for the browser.

[new-canvg](https://www.npmjs.com/package/new-canvg):
This supposedly fixes a memory leak in canvg. It's not easy to see how the memory leak was fixed in the [commit history](https://github.com/gios/new-canvg/commits/master) though.

[canvgc](https://www.npmjs.com/package/canvgc):
This is a compiler that runs on node that turns svg into javascript CanvasRenderingContext2D commands. It also uses the Cairo backed node `canvas`. The compiled javascript code can be used on the browser and probably in node too if you use the node Cairo `canvas`.

[grunt-canvgc](https://www.npmjs.com/package/grunt-canvgc):
This is a grunt plugin using [canvgc](https://www.npmjs.com/package/canvgc) to convert svg to javascript CanvasRenderingContext2D commands.

[canvg-browser](https://www.npmjs.com/package/canvg-browser):
This is a fork of the official canvg repo. It has merged a [somewhat recent commit from the offical canvg repo](https://github.com/bpmn-io/canvg-browser/commit/9777f43f7fbd320c5d9c33ff050b06e4e5b7bd11) on Tue Feb 16 03:30:46 UTC 2016. It also has dependencies on rgbcolor and stackblur so it doesn't include them in the package. It is exposed as a CommonJS module so you can `require` it and bundle it up for the browser. This should only work for the browser but you might be able to force it to work by using jsdom and node canvas.

So if you want to use canvg in node, I would go with [canvg](https://www.npmjs.com/package/canvg).

If you want to use in the browser, you have several options. I would go with one of the following:
1. add the [official canvg github repo](https://github.com/canvg/canvg) [to your package.json](https://stackoverflow.com/questions/23210437/npm-install-private-github-repositories-by-dependency-in-package-json). There a [commit that made canvg work for UMD which include CommonJS](https://github.com/canvg/canvg/blame/master/canvg.js#L20). So you should be able to require canvg. This will allow you to have the latest canvg updates.
2. Just use [canvg-browser](https://www.npmjs.com/package/canvg-browser). canvg-browser doesn't look like it gets anymore updates, even though the official canvg repo is still being updated. The latest merge from the official canvg was [this commit on Tue Feb 16 03:30:46 UTC 2016](https://github.com/bpmn-io/canvg-browser/commit/9777f43f7fbd320c5d9c33ff050b06e4e5b7bd11). It's not UMD so it not work with AMD and will only work with CommonJS.
3. If you have a problem with canvg-browser, you can try [canvg-origin](https://www.npmjs.com/package/canvg-origin). It was published on Tue Aug 30 12:44:17 UTC 2016 so it might have newer canvg code compared to canvg-browser. I haven't done any checking to compare that it is newer other than comparing the dates. It's pretty much the same as option 1 except that it is older and it has dependencies on rgbcolor and stackblur. It is a UMD module. It also has all those carriage returns I described above.
4. Use [canvg-fixed](https://www.npmjs.com/package/canvg-fixed). It's basically just an older version of option 3. It's publish date is Wed Jan 20 07:12:47 UTC 2016. It has unnecessary rgbcolor and stackblur files even though they are listed as dependencies. It is a UMD module.

**Comment by karim10** [comment]
Thank you @dosentmatter ! This helps a lot

**Comment by gabelerner** [comment]
canvg is now the official one! thanks for all the comments!
