### ISSUE TITLE
CSS : Cascading rules are ignored (found a workaround)

### ISSUE THREAD

**Issue by lapsus63** [canvg/canvg#535]
Hi,

Here is my SVG sample :

`<svg ... >`
`    <style type="text/css">.edge{stroke: rgba(238, 238, 204, 0.4)}.c0{stroke: rgba(66, 158, 120, 0.4)}.c1{stroke: rgba(93, 159, 98, 0.4)} ...</style>`
`    <g>`
`        <line class="edge" stroke-width="0.75" x1="92" y1="485" x2="11" y2="426"/>`
`        <line class="edge c0" stroke-width="0.75" x1="424" y1="426" x2="435" y2="397"/>`
`    </g>`
`</svg>`
`...`

Expected result :

1. Line 1 should be yellow
2. Line 2 should be green

Got result :

1. All lines are yellow

Explaination:

Cascading styles seems to be ignored or buggy. 
The first line having only one class "edge" inherits from yellow color as it should. 
The second line has "edge" + "c0" class. Only "edge" is interpreted.

Workaround:

I commented out this two lines from canvg.js but I don't really understand the side effects for this:
`//	if (specificity > existingSpecificity) {`
`	this.styles[name] = styles[name];`
`this.stylesSpecificity[name] = specificity;`
`//}`

**Comment by jemerald** [comment]
I think the problem is that all 3 of your CSS selector has the same specificity

```
.edge{stroke: rgba(238, 238, 204, 0.4)}
.c0{stroke: rgba(66, 158, 120, 0.4)}
.c1{stroke: rgba(93, 159, 98, 0.4)}
```

The `c0` selector is not anymore specific than `edge` (both only has one class selector). You can add `.edge` to the `.c0` and `.c1` to make them more specific:

```
.edge{stroke: rgba(238, 238, 204, 0.4)}
.edge.c0{stroke: rgba(66, 158, 120, 0.4)}
.edge.c1{stroke: rgba(93, 159, 98, 0.4)}
```

The implementation is a little off when compared to browser behaviour, which gives higher precedence to style of the same specificity that occurs later in the style list. (Having said that, it's still best to not have conflicting styles with the same specificity, which can cause unexpected behaviour when reordered)

I think the implementation should change to 

```
if (specificity >= existingSpecificity) {
  this.styles[name] = styles[name];
  this.stylesSpecificity[name] = specificity;
}
```

@gabelerner what do you think?

**Comment by gabelerner** [comment]
seems fine, i opened a PR. we also might want to backmerge latest changes from https://github.com/keeganstreet/specificity/blob/master/specificity.js at some point
