### ISSUE TITLE
Dependency on canvas

### ISSUE THREAD

**Issue by pgrm** [canvg/canvg#647]
Hello, I wanted to ask, why canvas was moved from dev dependency to dependency in https://github.com/canvg/canvg/commit/a6bc36b1e3e4bb010d5d135405317666462252c9 - could this be reverted and a new version released?

**Comment by EladBezalel** [comment]
Seems to break our build as well.

**Comment by SMJ93** [comment]
It's breaking our lerna script too, setting `"canvg": "1.5.3",` in our `package.json` fixes the issue for us.

**Comment by SGStino** [comment]
I'm guessing this also causes the following when running `npm install canvg`:
`node_modules\canvg\node_modules\canvas\src\canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\Canvas.cc) `

Quite a few users might be affected by this.

**Comment by hegelstad** [comment]
This is a breaking change on a minor patch version bump. It should be reverted ASAP.

**Comment by gabelerner** [comment]
@pgrm @EladBezalel  @SMJ93 @SGStino @hegelstad i unpublished `canvg@1.5.4` and we're back to `1.5.3`. I apologize for breaking your builds, but I do have a few questions now that we're all here. 
 First, there was a `devDependency` on (`canvas`)[https://www.npmjs.com/package/canvas] which I realized should actually be a `depency` to their `1.x` branch.  The reason being is that in the `node` world, we use this to (create child canvases)[https://github.com/canvg/canvg/blob/ff270383e72993b0519aa1b44938ca819944e0c0/src/canvg.js#L26] in the library.  It would break if you passed in a `2.x` implementation of `canvas` which is missing the `new Canvas()` constructor in favor of the `createCanvas` method.  I want to work towards upgrading this library to use the newer `canvas` but for now merely wanted to indicate that all users should be on the `1.x` branch of `canvas`.

- If you're using this on `node`, `canvas` is a pretty popular package w/ compile instructions.  You already should have it installed to use in `node` afaik since that's what you pass into the `canvg` function.  Are there any problems in this area?
- If you're using this on `browser`, I assume you're using `require` over something like including `jsdelivr`. What's the common policy here when the `browser` version doesn't rely on a package but the `node` one does? We use `rollup` to build 2 separate versions but it's the same package (has `browser` field in `package.json`).  Should I maintain two different packages or is there another solution that would prevent the `browser` side from having to install `canvas`.

Looking forward to the discussion.  Thanks for bringing this up.

**Comment by gabelerner** [comment]
@pgrm @EladBezalel @SMJ93 @SGStino @hegelstad what do you think if i added it as a `peerDependency` instead? that would at least warn if you're using an incompatible `canvas` on the `node` side?

**Comment by Pauan** [comment]
@gabelerner Fabric uses `canvas`, and we can into a lot of problems with it (it's one of the reasons we switched to canvg!)

Unfortunately I don't know of any way to have separate package dependencies for the browser and Node.

You can use `optionalDependencies`, but in that case the package will still be installed (even for the browser). But at least browser users won't need to [go through all the steps to install `canvas` on Windows](https://github.com/Automattic/node-canvas/wiki/Installation:-Windows).

You can use `"browser": { "canvas": false }`, that prevents bundlers (like Webpack) from including `canvas` in browser builds. But that still doesn't stop `canvas` from being *installed*.

So perhaps the best option is indeed to create a `canvg-node` package, which depends upon `canvas`

**Comment by gabelerner** [comment]
@pgrm @EladBezalel @SMJ93 @SGStino @hegelstad the PR above reverts the changes from https://github.com/canvg/canvg/commit/a6bc36b1e3e4bb010d5d135405317666462252c9#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 ... it's back to `devDependencies` but now also in `peerDependencies` and will warn (but not crash). thoughts?

**Comment by EladBezalel** [comment]
Thank you for the quick fix, i think `peerDependancy` should work just fine but in order to remove it from `devDependancy` you have to bump a major version since it's a breaking change.
All in all, you said you are working towards migrating to canvas 2 so i think this change can come with it (if you don't want to bump major version just like that)

**Comment by gabelerner** [comment]
it'll remain in dev for now.  will eventually move to peer and bump major version when i upgrade to canvas 2 per your point. thanks for the input!

**Comment by EladBezalel** [comment]
Ofc :)

Can you please publish the fix?

**Comment by gabelerner** [comment]
i don't think there's any rush to publish and i'd like to get in some more features into the release ... the `1.5.3` version that's out there is not broken.
