### ISSUE TITLE
There will be errors when using BASE64 image screenshots, in the latest version of Google Chrome

### ISSUE THREAD

**Issue by qq793931289** [canvg/canvg#651]

**Comment by qq793931289** [comment]
[base64.txt](https://github.com/canvg/canvg/files/2598682/base64.txt)

**Comment by qq793931289** [comment]
[base64.txt](https://github.com/canvg/canvg/files/2598686/base64.txt)

**Comment by qq793931289** [comment]
Just change '// render 3x3 grid so when we transform there's no white space on edges ' to 10*10;

**Comment by gabelerner** [comment]
thanks for taking the time to debug this. `3x3` was chosen because the bounds of the `patternTransform` aren't calculated in advance. if you do `10x10` then performance becomes impacted and who's to say that we'll need to do `20x20` later for some use cases. i think what's best is if there's a way to calculate how big of a space we need before rendering based on the specific `patternTransform`.

**Comment by qq793931289** [comment]
Yes, the above solution does affect performance; then another solution is made; the following code is added to the pattern:
`
//Correct image offset position
        var arrPosition = tempSvg.attributes['transform'].value.split(',');
        var xx = parseInt(parseFloat(arrPosition[4])/width);
        var yy = parseInt(parseFloat(arrPosition[5])/height) ;
        cctx.translate(-width*xx,-height*yy);
`
Solved this problem! This library is very easy to use, thank you again!
