### ISSUE TITLE
Support what versions of es on node/browsers?

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#654]
https://github.com/canvg/canvg/pull/653 has some discussion

Generally:
- What node versions do we want to support?
- What browsers do we want to support?

This will take effect in the `2.0` release.

My suggestions:
- Drop support for `node <6.x` and bump to `node 8.x` so we can use es6/async/await natively. `node 6` is almost at end of LTS anyways.
- Target `es6` for browsers http://kangax.github.io/compat-table/es6/. `IE11` no longer supported.

**Comment by brettz9** [comment]
I'm partial to using `browserslist` to express any targets so that the likes of `eslint-plugin-compat` and `@babel/preset-env` can respectively lint and compile the code to support the targets (noting that "node" can be one of the targets as well as browser versions or percent market coverage: see https://github.com/browserslist/browserslist#full-list ). 

With Rollup + Babel, one can use the latest features in source, and have the distributed files support the desired targets. One could choose anywhere from 100% coverage -> to your suggested targets -> to requiring consumers of canvg to do their own compilation. I'm not personally too particular on the choice of targets (if any), except that I favor expressing any targets in this manner.

**Comment by brettz9** [comment]
SGTM...

**Comment by gabelerner** [comment]
@brettz9 i don't have that much experience w/ rollup/browserlist/etc. so i'll leave this open to you when you get a next chance and just keep working on feature issues.

**Comment by brettz9** [comment]
Sure... I'm backlogged currently due to the fact that while I prepared a PR for ES6 Modules, puppeteer currently breaks with them so I can't confirm testing is ok... Looks like a fix is on the way, however: https://github.com/GoogleChrome/puppeteer/issues/3382

**Comment by brettz9** [comment]
Related to this, with the recent TypeScript changes, I am not able to set up the full linting environment with a local `yarn` install.

**Comment by dangreen** [comment]
@gabelerner I think we can close it

**Comment by gabelerner** [comment]
agreed. our targets are well defined today and people can open PRs if they want different support.
