### ISSUE TITLE
text-transform not supported

### ISSUE THREAD

**Issue by HackbrettXXX** [canvg/canvg#701]
The [text-transform](https://www.w3.org/TR/css-text-3/#text-transform-property) attribute is not supported. See this fiddle: http://jsfiddle.net/zes67d89/. As far as I could see, it is not on the [list of unsupported text features](https://github.com/canvg/canvg/issues/668).

**Comment by gabelerner** [comment]
yea a lot of these come from css not svg, and svg supports css so it's difficult for me to pick and choose which css features to support vs not as there are way too many of them. going to just lump this into that other thread to keep track of it as a currently unsupported feature but somebody can then open a PR for it. should be fairly simple to implement since js supports casing.
