### ISSUE TITLE
Invalid font-size breaks tspan position

### ISSUE THREAD

**Issue by mistic100** [canvg/canvg#705]
Demo of the problem : https://stackblitz.com/edit/js-uelktv

I am getting SVG from an external system which may contain some invalid data, the SVG is correctly displayed but it breaks canvg rendering.

In the this specific case the combination of :
 - `font-size="undefinedpx"` on the `text` (invalid)
 - `x="500" dy="0em"` on the `tspan` (valid)
prevents the text from rendering

If you remove ANY of the said attributes it works, even if you leave the invalid font-size but remove the tspan position.

**Comment by gabelerner** [comment]
attaching to wont fix https://github.com/canvg/canvg/issues/671 because i don't think it's canvg's job to validate SVG. failure on invalid properties is expected  if the user is feeding it bad data -- they should instead pre-process on their end to make it good.

**Comment by mistic100** [comment]
Aren't the point of this library to render SVG like a browser will do ?
It would so much simpler to just ignore invalid data, more over when it fails in some specific case. How do you explain is works when the tspan doesn't have a position ?

**Comment by gabelerner** [comment]
the point of this library is to render valid svg. browsers are better about ignoring it but even they throw errors when you have something truly invalid for svg, html, etc.

that said, just because it's sitting in `wont fix` doesn't mean somebody won't fix it, i just choose not to. if you want, you can open a PR to fix it and i'll merge it.

**Comment by mistic100** [comment]
fair enough :-)
