### ISSUE TITLE
Svg emSize is not updated if the font is defined as shorthand property

### ISSUE THREAD

**Issue by fargyriou** [canvg/canvg#717]

**Comment by gabelerner** [comment]
do you have an example svg that breaks?

**Comment by artemis0523** [comment]
Check for example this svg. 
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 60" width="300" height="60"><g style="font: bold 30px Tahoma;" transform="translate(0 0)">
<text dy="1.5em" fill="rgb(94,103,130)" text-anchor="middle" transform="translate(120 5)">My template Label</text></g></svg>

The problem is that the svg.emSize is not updated when the font is created from the shorthand css properties. I think the value has to be updated also after this line: ctx.font = this.style('font').value;

**Comment by fargyriou** [comment]
Check for example this svg. 
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 60" width="300" height="60"><g style="font: bold 30px Tahoma;" transform="translate(0 0)">
<text dy="1.5em" fill="rgb(94,103,130)" text-anchor="middle" transform="translate(120 5)">My template Label</text></g></svg>
```

The problem is that the svg.emSize is not updated when the font is created from the shorthand css properties. I think the value has to be updated also after this line: ctx.font = this.style('font').value;
