### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by dangreen** [canvg/canvg#744]
@gabelerner Hey 👋 

Fyi: currently I'm working on refactoring of canvg in [my fork](https://github.com/TrigenSoftware/flexis-canvg).

If you like it, we can merge it in future, when i'm done refactoring.

Progress:

- [x] Rewrite to TypeScript;
- [x] Сheck if it works;
- [x] Rewrite tests;
- [x] Apply [fixes](https://github.com/canvg/canvg/pulls) from main repo.
- [x] Write docs;

**Comment by gabelerner-kernel** [comment]
yea that's desired, i wish i had time to do that. it'd be also nice if we move the modules independently so we have a `rectangle.ts` and a `path.ts` and etc. corresponding to each `svg.Element` ... would it help to make you a collaborator on the main repo and you can start piecemealing it one by one? a big refactor would be hard to merge in but i'd happily merge independent modules one at a time. something like:

1) add typescript build system since js is backwards compatible
2) move svg.Element.rect to `rect.ts`
3) continue for each element until done!

thoughts on this?

**Comment by dangreen** [comment]
@gabelerner-kernel 

https://github.com/TrigenSoftware/flexis-canvg/tree/master/src

It's already in TypeScript and already splitted to files :-)

**Comment by gabelerner** [comment]
Yea that's really neat ... I'm wondering what a good way would be to merge it into canvg but I can just visually review a big PR over a weekend and run through the test suite.

I completely approve of this direction and it's very exciting! If you want, you can just work on it in a branch here? Let me know how I can best support this!

**Comment by dangreen** [comment]
https://github.com/canvg/canvg/pull/751
