### ISSUE TITLE
canvg2 text-anchor with text/tspan not rendered properly

### ISSUE THREAD

**Issue by tjohannto** [canvg/canvg#782]
I am using the current version of canvg : https://cdn.jsdelivr.net/npm/canvg/dist/browser/canvg.min.js (assuming this is v2.0.0) but https://cdn.jsdelivr.net/npm/canvg@2.0.0-beta.0/dist/browser/canvg.min.js also does not work...

I use tspan elements in a text element and when I export this to canvas using canvg the element is not rendered correctly:

SVG:
![image](https://user-images.githubusercontent.com/45257386/68381713-9a8b7c00-0152-11ea-8ef0-02a191f536d7.png)

Canvas:
![image](https://user-images.githubusercontent.com/45257386/68381738-a4ad7a80-0152-11ea-8865-62dc537ff315.png)

example code: https://jsfiddle.net/gothmogg/tdxncur0/

Is there a version of canvg where this is rendered correctly or am I doing s.th. wrong?

**Comment by dangreen** [comment]
@tjohannto Current beta version is [3.0.0-beta.2](https://www.npmjs.com/package/canvg/v/3.0.0-beta.2)

**Comment by tjohannto** [comment]
> @tjohannto Current beta version is [3.0.0-beta.2](https://www.npmjs.com/package/canvg/v/3.0.0-beta.2)

Thanks, I can't find any CDN link for usage in jsFiddle or similar. Is there any?

**Comment by dangreen** [comment]
@tjohannto https://unpkg.com/canvg@3.0.0-beta.2/lib/umd.js

Browser example: https://github.com/canvg/canvg#example

**Comment by tjohannto** [comment]
> @tjohannto https://unpkg.com/canvg@3.0.0-beta.2/lib/umd.js
> 
> Browser example: https://github.com/canvg/canvg#example

Thank you.
Result is the same:
![image](https://user-images.githubusercontent.com/45257386/68382748-a1b38980-0154-11ea-9161-094afb3bc04d.png)

https://jsfiddle.net/gothmogg/0j541nav/

**Comment by gabelerner** [comment]
here's a simplified version https://jsfiddle.net/4tbfpj7v/1/

**Comment by gabelerner** [comment]
@tjohannto try now on the latest beta release

**Comment by tjohannto** [comment]
Hi, I have updated my jsFiddlet with the current beta (https://unpkg.com/canvg@3.0.0-beta.4/lib/umd.js)

https://jsfiddle.net/gothmogg/0j541nav/

The issue is resolved. Thank you.

**Comment by abetusk** [comment]
Has there been a regression on this issue? I have a the following SVG:

```
<svg version="1.1" id="Frame_0" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="190px" height="317px">
  <rect rx="10" x="18" y="267" width="154" height="20" fill="#efefef" > </rect>
  <text x="0" y="0" id="_text_name">
    <tspan  id="_tspan_name"  x="95"  y="283"  style="fill:rgb(50,50,50);font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;font-size:15px;font-family:'Caviar Dreams';-inkscape-font-specification:'Caviar Dreams, Bold';font-variant-ligatures:normal;font-variant-caps:normal;font-variant-numeric:normal;font-feature-settings:normal;text-align:center;writing-mode:lr-tb;text-anchor:middle;stroke-width:0.26458332px">middle text</tspan>
  </text>
</svg>
```

with the `middle text` not being centered. The text looks to be left justified with an anchor point in the middle.

As far as I can tell, I'm using `canvg` version `3.6.1`.

On the left is what I would expect (rendered with Firefox, say) and on the right is what my version (`3.6.1`?) renders:

| expected | `canvg 3.6.1` |
|---|---|
|  ![expected_text](https://user-images.githubusercontent.com/1406122/128289447-9d716d38-da5d-4ddd-8979-be2af0693620.png) | ![canvg_bad_text](https://user-images.githubusercontent.com/1406122/128289460-1c029fe6-0dd0-4966-859f-ea6ceb78e509.png) |


I'm happy to provide a more in depth working example but the above "fixed" [link](https://jsfiddle.net/gothmogg/0j541nav/) also does not work and is using (afaict) `canvg` version `3.3.6`.

FYI, when altering the `text-anchor` field in the `tspan` to be `left` instead of `middle`, the rendered SVG looks like the incorrect rendering from `canvg`. If I had to hazard a guess, it would be that `canvg` is not picking up the `text-anchor` property.

**Comment by abetusk** [comment]
Ah! It looks like setting the `text-anchor` property explicitly in the `tspan` works.

This renders correctly in `canvg`:

```
<svg version="1.1" id="Frame_0" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="190px" height="317px"><rect rx="10" x="18" y="267" width="154" height="20" fill="#efefef" > </rect><text x="0" y="0" id="_text_name">
<tspan  id="_tspan_name"  x="95"  y="283"  text-anchor="middle" style="text-align:middle;fill:rgb(50,50,50);font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;font-size:15px;font-family:'Caviar Dreams';-inkscape-font-specification:'Caviar Dreams, Bold';font-variant-ligatures:normal;font-variant-caps:normal;font-variant-numeric:normal;font-feature-settings:normal;text-align:center;writing-mode:lr-tb;text-anchor:middle;stroke-width:0.26458332px">middle text</tspan></text> </svg>
```

Whereas the original example above does not:

```
<svg version="1.1" id="Frame_0" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="190px" height="317px"><rect rx="10" x="18" y="267" width="154" height="20" fill="#efefef" > </rect><text x="0" y="0" id="_text_name">
<tspan  id="_tspan_name"  x="95"  y="283"  style="text-align:middle;fill:rgb(50,50,50);font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;font-size:15px;font-family:'Caviar Dreams';-inkscape-font-specification:'Caviar Dreams, Bold';font-variant-ligatures:normal;font-variant-caps:normal;font-variant-numeric:normal;font-feature-settings:normal;text-align:center;writing-mode:lr-tb;text-anchor:middle;stroke-width:0.26458332px">middle text</tspan></text> </svg>
```

with the difference being the `text-align="middle"` property being explicitly put in to the `tspan` instead of the `style` list.

Please let me know if you'd like me to open a separate issue.
